version: '3.8'

services:
  api_gateway:
    build: ./api-gateway
    container_name: api_gateway
    ports:
      - 7778:7777
    depends_on:
      - booking_service
      - hotel_service
      - user_service
      - broker
    networks:
      - mynetwork

  user_service:
    build: ./user_service
    container_name: user_service
    environment:
      - PG_URL=postgres://postgres:Abdu0811@user_postgres:5432/imtihon_5?sslmode=disable
    ports:
      - 8888:8888
    depends_on:
      - user_postgres
      - redis
      - broker
    networks:
      - mynetwork

  hotel_service:
    build: ./hotel_service
    container_name: hotel_service_container
    environment:
      - MONGO_URL=mongodb://hotel_mongo:27017/hotels
    ports:
      - 9999:9999
    depends_on:
      - hotel_mongo
      - broker
    networks:
      - mynetwork

  booking_service:
    build: ./booking_service
    container_name: booking_service_container
    environment:
      - MONGO_URL=mongodb://booking_mongo:27017/booking
    ports:
      - 9090:9090
    depends_on:
      - booking_mongo
      - broker
    networks:
      - mynetwork

  notification_service:
    build: ./notification_service
    container_name: notification_service_container
    ports:
      - "8083:8083"
      - "8887:8887"
    depends_on:
      - broker
    networks:
      - mynetwork

  broker:
    image: apache/kafka:latest
    container_name: kafka_broker
    ports:
      - "9092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    networks:
      - mynetwork

  user_postgres:
    image: postgres:14-alpine
    container_name: user_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abdu0811
      POSTGRES_DB: imtihon_5
      PGDATA: /var/lib/postgresql/data
    volumes:
      - user-db-data:/var/lib/postgresql/data
      - ./user_service/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d imtihon_5 || exit 1"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
    networks:
      - mynetwork

  migrate_user:
    image: migrate/migrate
    volumes:
      - ./user_service/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:Abdu0811@user_postgres:5432/imtihon_5?sslmode=disable", "up"]
    depends_on:
      user_postgres:
        condition: service_healthy
    networks:
      - mynetwork

  hotel_mongo:
    image: mongo:latest
    container_name: hotel_mongo
    environment:
      MONGO_INITDB_DATABASE: Hotels
    ports:
      - "27018:27017"
    volumes:
      - hotel-db-data:/data/db
    networks:
      - mynetwork

  booking_mongo:
    image: mongo:latest
    container_name: booking_mongo
    environment:
      MONGO_INITDB_DATABASE: Booking
    ports:
      - "27019:27017"
    volumes:
      - booking-db-data:/data/db
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6378:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q PONG || exit 1"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  user-db-data:
  hotel-db-data:
  booking-db-data:
