// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: hotelproto/hotel.proto

package hotelproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hotel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HotelId  string `protobuf:"bytes,1,opt,name=hotelId,proto3" json:"hotelId,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Rating   int32  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Address  string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *Hotel) Reset() {
	*x = Hotel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotelproto_hotel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hotel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hotel) ProtoMessage() {}

func (x *Hotel) ProtoReflect() protoreflect.Message {
	mi := &file_hotelproto_hotel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hotel.ProtoReflect.Descriptor instead.
func (*Hotel) Descriptor() ([]byte, []int) {
	return file_hotelproto_hotel_proto_rawDescGZIP(), []int{0}
}

func (x *Hotel) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

func (x *Hotel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hotel) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Hotel) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Hotel) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type HotelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Rating   int32  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Address  string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *HotelRequest) Reset() {
	*x = HotelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotelproto_hotel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotelRequest) ProtoMessage() {}

func (x *HotelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotelproto_hotel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotelRequest.ProtoReflect.Descriptor instead.
func (*HotelRequest) Descriptor() ([]byte, []int) {
	return file_hotelproto_hotel_proto_rawDescGZIP(), []int{1}
}

func (x *HotelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HotelRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *HotelRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *HotelRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type HotelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HotelId string `protobuf:"bytes,1,opt,name=hotelId,proto3" json:"hotelId,omitempty"`
}

func (x *HotelResponse) Reset() {
	*x = HotelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotelproto_hotel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotelResponse) ProtoMessage() {}

func (x *HotelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hotelproto_hotel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotelResponse.ProtoReflect.Descriptor instead.
func (*HotelResponse) Descriptor() ([]byte, []int) {
	return file_hotelproto_hotel_proto_rawDescGZIP(), []int{2}
}

func (x *HotelResponse) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotelproto_hotel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_hotelproto_hotel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_hotelproto_hotel_proto_rawDescGZIP(), []int{3}
}

type ListHotels struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hotel []*Hotel `protobuf:"bytes,1,rep,name=hotel,proto3" json:"hotel,omitempty"`
}

func (x *ListHotels) Reset() {
	*x = ListHotels{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotelproto_hotel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHotels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHotels) ProtoMessage() {}

func (x *ListHotels) ProtoReflect() protoreflect.Message {
	mi := &file_hotelproto_hotel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHotels.ProtoReflect.Descriptor instead.
func (*ListHotels) Descriptor() ([]byte, []int) {
	return file_hotelproto_hotel_proto_rawDescGZIP(), []int{4}
}

func (x *ListHotels) GetHotel() []*Hotel {
	if x != nil {
		return x.Hotel
	}
	return nil
}

type HotelRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HotelRes) Reset() {
	*x = HotelRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotelproto_hotel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotelRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotelRes) ProtoMessage() {}

func (x *HotelRes) ProtoReflect() protoreflect.Message {
	mi := &file_hotelproto_hotel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotelRes.ProtoReflect.Descriptor instead.
func (*HotelRes) Descriptor() ([]byte, []int) {
	return file_hotelproto_hotel_proto_rawDescGZIP(), []int{5}
}

func (x *HotelRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Room struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId        string `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	HotelId       string `protobuf:"bytes,2,opt,name=hotelId,proto3" json:"hotelId,omitempty"`
	RoomType      string `protobuf:"bytes,3,opt,name=roomType,proto3" json:"roomType,omitempty"`
	PricePerNight int32  `protobuf:"varint,4,opt,name=pricePerNight,proto3" json:"pricePerNight,omitempty"`
	Availability  bool   `protobuf:"varint,5,opt,name=availability,proto3" json:"availability,omitempty"`
}

func (x *Room) Reset() {
	*x = Room{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotelproto_hotel_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_hotelproto_hotel_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_hotelproto_hotel_proto_rawDescGZIP(), []int{6}
}

func (x *Room) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Room) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

func (x *Room) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *Room) GetPricePerNight() int32 {
	if x != nil {
		return x.PricePerNight
	}
	return 0
}

func (x *Room) GetAvailability() bool {
	if x != nil {
		return x.Availability
	}
	return false
}

type RoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HotelId       string `protobuf:"bytes,1,opt,name=hotelId,proto3" json:"hotelId,omitempty"`
	RoomType      string `protobuf:"bytes,2,opt,name=roomType,proto3" json:"roomType,omitempty"`
	PricePerNight int32  `protobuf:"varint,3,opt,name=pricePerNight,proto3" json:"pricePerNight,omitempty"`
	Availability  bool   `protobuf:"varint,4,opt,name=availability,proto3" json:"availability,omitempty"`
}

func (x *RoomRequest) Reset() {
	*x = RoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotelproto_hotel_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomRequest) ProtoMessage() {}

func (x *RoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotelproto_hotel_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomRequest.ProtoReflect.Descriptor instead.
func (*RoomRequest) Descriptor() ([]byte, []int) {
	return file_hotelproto_hotel_proto_rawDescGZIP(), []int{7}
}

func (x *RoomRequest) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

func (x *RoomRequest) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *RoomRequest) GetPricePerNight() int32 {
	if x != nil {
		return x.PricePerNight
	}
	return 0
}

func (x *RoomRequest) GetAvailability() bool {
	if x != nil {
		return x.Availability
	}
	return false
}

type RoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *RoomResponse) Reset() {
	*x = RoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotelproto_hotel_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomResponse) ProtoMessage() {}

func (x *RoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hotelproto_hotel_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomResponse.ProtoReflect.Descriptor instead.
func (*RoomResponse) Descriptor() ([]byte, []int) {
	return file_hotelproto_hotel_proto_rawDescGZIP(), []int{8}
}

func (x *RoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type ListRooms struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room []*Room `protobuf:"bytes,1,rep,name=room,proto3" json:"room,omitempty"`
}

func (x *ListRooms) Reset() {
	*x = ListRooms{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotelproto_hotel_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRooms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRooms) ProtoMessage() {}

func (x *ListRooms) ProtoReflect() protoreflect.Message {
	mi := &file_hotelproto_hotel_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRooms.ProtoReflect.Descriptor instead.
func (*ListRooms) Descriptor() ([]byte, []int) {
	return file_hotelproto_hotel_proto_rawDescGZIP(), []int{9}
}

func (x *ListRooms) GetRoom() []*Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type RoomRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RoomRes) Reset() {
	*x = RoomRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotelproto_hotel_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomRes) ProtoMessage() {}

func (x *RoomRes) ProtoReflect() protoreflect.Message {
	mi := &file_hotelproto_hotel_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomRes.ProtoReflect.Descriptor instead.
func (*RoomRes) Descriptor() ([]byte, []int) {
	return file_hotelproto_hotel_proto_rawDescGZIP(), []int{10}
}

func (x *RoomRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_hotelproto_hotel_proto protoreflect.FileDescriptor

var file_hotelproto_hotel_proto_rawDesc = []byte{
	0x0a, 0x16, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x6f, 0x74,
	0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83, 0x01, 0x0a, 0x05, 0x48, 0x6f, 0x74,
	0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x70,
	0x0a, 0x0c, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x22, 0x29, 0x0a, 0x0d, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x07, 0x0a, 0x05, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x2a, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x74, 0x65,
	0x6c, 0x73, 0x12, 0x1c, 0x0a, 0x05, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x06, 0x2e, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x05, 0x68, 0x6f, 0x74, 0x65, 0x6c,
	0x22, 0x24, 0x0a, 0x08, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x9e, 0x01, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x6d, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a,
	0x0d, 0x70, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x4e, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x70, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x4e, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x22, 0x8d, 0x01, 0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a,
	0x0d, 0x70, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x4e, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x70, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x4e, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x22, 0x26, 0x0a, 0x0c, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22,
	0x26, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x19, 0x0a, 0x04,
	0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0x23, 0x0a, 0x07, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x8e, 0x03, 0x0a,
	0x0c, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a,
	0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x12, 0x0d, 0x2e, 0x48,
	0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x48, 0x6f,
	0x74, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x62, 0x79, 0x49, 0x64, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x12, 0x0e, 0x2e, 0x48, 0x6f,
	0x74, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x06, 0x2e, 0x48, 0x6f,
	0x74, 0x65, 0x6c, 0x12, 0x23, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x48, 0x6f, 0x74,
	0x65, 0x6c, 0x73, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0b, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x12, 0x06, 0x2e, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x1a,
	0x09, 0x2e, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x0b, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x12, 0x0e, 0x2e, 0x48, 0x6f, 0x74, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x09, 0x2e, 0x48, 0x6f, 0x74, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x12, 0x0c, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x23, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x62, 0x79, 0x49, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x0d,
	0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x05, 0x2e,
	0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x21, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x6f,
	0x6f, 0x6d, 0x73, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0a, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x05, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x1a, 0x08, 0x2e, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x0d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x1a, 0x08, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x42, 0x0e, 0x5a,
	0x0c, 0x2e, 0x2f, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hotelproto_hotel_proto_rawDescOnce sync.Once
	file_hotelproto_hotel_proto_rawDescData = file_hotelproto_hotel_proto_rawDesc
)

func file_hotelproto_hotel_proto_rawDescGZIP() []byte {
	file_hotelproto_hotel_proto_rawDescOnce.Do(func() {
		file_hotelproto_hotel_proto_rawDescData = protoimpl.X.CompressGZIP(file_hotelproto_hotel_proto_rawDescData)
	})
	return file_hotelproto_hotel_proto_rawDescData
}

var file_hotelproto_hotel_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_hotelproto_hotel_proto_goTypes = []any{
	(*Hotel)(nil),         // 0: Hotel
	(*HotelRequest)(nil),  // 1: HotelRequest
	(*HotelResponse)(nil), // 2: HotelResponse
	(*Empty)(nil),         // 3: Empty
	(*ListHotels)(nil),    // 4: ListHotels
	(*HotelRes)(nil),      // 5: HotelRes
	(*Room)(nil),          // 6: Room
	(*RoomRequest)(nil),   // 7: RoomRequest
	(*RoomResponse)(nil),  // 8: RoomResponse
	(*ListRooms)(nil),     // 9: ListRooms
	(*RoomRes)(nil),       // 10: RoomRes
}
var file_hotelproto_hotel_proto_depIdxs = []int32{
	0,  // 0: ListHotels.hotel:type_name -> Hotel
	6,  // 1: ListRooms.room:type_name -> Room
	1,  // 2: HotelService.CreateHotel:input_type -> HotelRequest
	2,  // 3: HotelService.GetbyIdHotel:input_type -> HotelResponse
	3,  // 4: HotelService.GetAllHotels:input_type -> Empty
	0,  // 5: HotelService.UpdateHotel:input_type -> Hotel
	2,  // 6: HotelService.DeleteHotel:input_type -> HotelResponse
	7,  // 7: HotelService.CreateRoom:input_type -> RoomRequest
	8,  // 8: HotelService.GetbyIdRoom:input_type -> RoomResponse
	3,  // 9: HotelService.GetAllRooms:input_type -> Empty
	6,  // 10: HotelService.UpdateRoom:input_type -> Room
	8,  // 11: HotelService.DeleteRoom:input_type -> RoomResponse
	2,  // 12: HotelService.CreateHotel:output_type -> HotelResponse
	0,  // 13: HotelService.GetbyIdHotel:output_type -> Hotel
	4,  // 14: HotelService.GetAllHotels:output_type -> ListHotels
	5,  // 15: HotelService.UpdateHotel:output_type -> HotelRes
	5,  // 16: HotelService.DeleteHotel:output_type -> HotelRes
	8,  // 17: HotelService.CreateRoom:output_type -> RoomResponse
	6,  // 18: HotelService.GetbyIdRoom:output_type -> Room
	9,  // 19: HotelService.GetAllRooms:output_type -> ListRooms
	10, // 20: HotelService.UpdateRoom:output_type -> RoomRes
	10, // 21: HotelService.DeleteRoom:output_type -> RoomRes
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_hotelproto_hotel_proto_init() }
func file_hotelproto_hotel_proto_init() {
	if File_hotelproto_hotel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hotelproto_hotel_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Hotel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hotelproto_hotel_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*HotelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hotelproto_hotel_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*HotelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hotelproto_hotel_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hotelproto_hotel_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ListHotels); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hotelproto_hotel_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*HotelRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hotelproto_hotel_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Room); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hotelproto_hotel_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*RoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hotelproto_hotel_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*RoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hotelproto_hotel_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ListRooms); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hotelproto_hotel_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*RoomRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hotelproto_hotel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hotelproto_hotel_proto_goTypes,
		DependencyIndexes: file_hotelproto_hotel_proto_depIdxs,
		MessageInfos:      file_hotelproto_hotel_proto_msgTypes,
	}.Build()
	File_hotelproto_hotel_proto = out.File
	file_hotelproto_hotel_proto_rawDesc = nil
	file_hotelproto_hotel_proto_goTypes = nil
	file_hotelproto_hotel_proto_depIdxs = nil
}
